### ISSUE TITLE
ExtraUtils2 boomerang(迴力鏢) crash

### ISSUE THREAD

**Issue by alan6716** [TeamSLTW/SLCP3#17]
Crash Report:
http://pastebin.com/SV2fwkrq

Version:
SmileLawnCompletePack3 Lite5

額外加裝：
SlashBlade-mc1.10.2-r27

詳細：
在單人端使用，正常。
昨天在伺服器上製作出迴力鏢並使用，正常。
今天再開伺服器上線使用迴力鏢，單人端 Crash，Server 沒事。
--迴力鏢拿在手上，右鍵後準備擲出的瞬間發生 Crash。

**Comment by frank89722** [comment]
有試過移除SlashBlade嗎？

**Comment by alan6716** [comment]
我更新到 SlashBlade-mc1.10.2-r29b
目前暫時回力鏢不會 crash，可能明天要再測試看看會不會又鬼打牆。
