### ISSUE TITLE
活塞複製BUG

### ISSUE THREAD

**Issue by Threeyearsmio** [TeamSLTW/SLCP3#19]
當手上持有1個活塞&黏性活塞 放出去時變成空手 但此時還可以繼續放活塞 並回收後越來越多
就像是活塞從來沒從手上消失一樣

**Comment by Threeyearsmio** [comment]
阿 看到巴哈有人回報活塞問題了 不好意思orz

**Comment by frank89722** [comment]
問題存在很久了，但是我還找不到原因

**Comment by frank89722** [comment]
Fixed in 1.2.0
