### ISSUE TITLE
Minecraft crash 創世神崩潰

### ISSUE THREAD

**Issue by NoTrueID7** [TeamSLTW/SLCP3#20]
[crash-2017-01-25_23.33.01-client.txt](https://github.com/TeamSLTW/SLCP3/files/730123/crash-2017-01-25_23.33.01-client.txt)

版本:1.10.2-Forge 12.18.3.2185
Versions:1.10.2-Forge 12.18.3.2185
連開都不能Q3Q

**Comment by frank89722** [comment]
記憶體不足，另外，你要回報的是模組包版本不是forge版本

**Comment by NoTrueID7** [comment]
謝謝~

2017-01-25 23:53 GMT+08:00 frank89722 <notifications@github.com>:
