### ISSUE TITLE
可以幫我看一下是哪裡有問題嗎?~

### ISSUE THREAD

**Issue by NoTrueID7** [TeamSLTW/SLCP3#21]
[crash-2017-02-02_19.31.23-client.txt](https://github.com/TeamSLTW/SLCP3/files/750273/crash-2017-02-02_19.31.23-client.txt)

版本      1.10.2-LiteLoader1.10.2-1.10.2-forge1.10.2-12.18.3.2185

登入可以玩大約20 sec然後就不能玩惹qq
求幫助

**Comment by frank89722** [comment]
郭p4
