### ISSUE TITLE
無法啓動游戲

### ISSUE THREAD

**Issue by SnowB0ll** [TeamSLTW/SLCP3#22]
游戲版本：SLCP3 1.1.2
點了PLAY但是會crash
crash report:  http://pastebin.com/8m24ivad
給啓動器6G和12G過都是一樣無法啓動 其他模組包也是一樣
這是我的電腦問題還是其他的什麽？
![java](https://cloud.githubusercontent.com/assets/25641334/22744096/9e956654-ee1c-11e6-9376-be91c2cb073b.PNG)
![default](https://cloud.githubusercontent.com/assets/25641334/22744097/9e9bfac8-ee1c-11e6-9945-0c823c43ccae.PNG)

**Comment by frank89722** [comment]
只有我這包開不起來嗎?
原版開得起來嗎?

**Comment by SnowB0ll** [comment]
原版開的起來
1.10的模組包都打不開（目前現在測試過 DW 和 SLCP

**Comment by frank89722** [comment]
最近有更新nvidia驅動對吧?

**Comment by SnowB0ll** [comment]
嗯 它自動更新的
怎麽了

**Comment by frank89722** [comment]
降回去
