### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Stupidguy115** [TeamSLTW/SLCP3#24]
Report內容
http://pastebin.com/N8z040AC
已經好多次這樣子crash了
我在用SmileLawnCompletePack3 Lite版 V1.1
最初以為機器問題而發生的crash
因為我在建Big Reactors的Turbine剛放下Turbine的Fluid Port就crash下去
但不是MCEdit把東西刪了crash依舊存在
回顧再早一點的動作就是地獄放下RFTool的 Builder Block掘礦
當我再進遊戲去把地獄的機器打掉就立即再crash
之後每次再進地圖就立即crash
我只好把之前的地圖備份拿來使用 才可以再正常遊玩一下下
如果玩多一兩個小時後這crash還是會出現
掛著時也會crash 打怪時也會crash
請問這會是什麼問題??

**Comment by frank89722** [comment]
你先試試看把你的參數全砍了只留記憶體

**Comment by frank89722** [comment]
又或是用用看我建議的參數

**Comment by Stupidguy115** [comment]
http://pastebin.com/K4Eb34di

crash依舊出現

**Comment by Stupidguy115** [comment]
如果只用你的參數是
http://pastebin.com/hE7VL1Vv

**Comment by frank89722** [comment]
地圖壞了不是模組包的bug，你可以開備份，技術方面我大概是幫不了你了

**Comment by Stupidguy115** [comment]
那知不知道大約會是什麼原因令地圖會壞??

**Comment by frank89722** [comment]
不會有人知道的，開備份吧。

**Comment by Stupidguy115** [comment]
好的 謝謝
