### ISSUE TITLE
請問是否地圖又壞檔了 T_T??

### ISSUE THREAD

**Issue by Stupidguy115** [TeamSLTW/SLCP3#26]
Crash report在此
https://pastebin.com/j0uRqmsT

繼之前lite版怎樣重開新地圖都會壞地圖之後
我決定來到完整版v1.1.2的懷抱了
由1月16日重玩至今
直到我前天剛去了找draconic evolution的紅龍玩
當我找到第一隻時發現帶不夠電池
所以用了/home指令回一回家
拿完電池再走回去時發現 紅龍消失了
在島中心打著雷 這代表著紅龍應該死去了吧??
可是水晶我一顆都沒有打 難道是紅龍有bugs??
所以帶著好奇心去找第2第3隻
可是發現在終界內 每隻龍的出現(包括紅龍, 終界龍)
地圖上都會粉紅一片 我本以為這是夜視效果問題
可是關了之後 整個世界都太黑了, 所以我只好看著粉紅一片去打
直到龍死後一切回復正常
就這樣安全找到第2第3隻紅龍, 也安全地打完了
可是回到overworld 弄好用solar flux reborn的最高階發電機後
正在弄32*32*32大size 的reactor發電機的ae自動合成時
弄到一半後crash出現了 又是連地圖都沒得進的crash T_T"""
這次還沒有任何backup呢........

**Comment by frank89722** [comment]
不可能沒有backup吧，明明有自動備份模組

**Comment by Stupidguy115** [comment]
因為之前一直想重灌window
沒可能只有我自己玩lite版會一直死地圖
所以重灌了
但只記得backup起本身地圖save
忘了自動backup的……

**Comment by frank89722** [comment]
移除draconic,或把draconic 降到跟1.1.1一樣的版本
