### ISSUE TITLE
BR和史特林引擎的問題

### ISSUE THREAD

**Issue by cdhn6469** [TeamSLTW/SLCP3#28]
首先，br疑似礦典有問題，控制器只能用一般的黃鈾錠，但是一般的黃鈾錠無法取得，黃礦拿去燒會變成ie的鈾錠，所以無法製作控制器，再來是史特林引擎，製作時黃金渦輪風扇會歸還出一個鐵製的渦輪風扇，這是設定還是bug?  。

**Comment by frank89722** [comment]
br這個是bug史特林引擎待查證

**Comment by frank89722** [comment]
Fixed in 1.2.0 b1
