### ISSUE TITLE
SFM複製BUG

### ISSUE THREAD

**Issue by neko1204** [TeamSLTW/SLCP3#29]
BUG模組: Steve's factory manager
使用Item value撿取物品至箱子，物品會直接塞滿箱子。
例:
如我丟一個 Diamond 在地上讓他撿取，
![01](https://cloud.githubusercontent.com/assets/28192991/25555868/cc24973e-2d23-11e7-97a0-bac69f78b56f.png)

設定Out put箱子的每一個格子均會放一個Diamond。
![02](https://cloud.githubusercontent.com/assets/28192991/25555869/cc2d6120-2d23-11e7-8724-682e3685d54a.png)

此項BUG可以複製每一個物品，
若使用 Mekanism 的 Cardboard box ，
有少數的物品被包起來，
模組的連鎖反應，會造成遊戲個人端崩潰 (如: AE2的 ME drive)。
目前發現會跟Waila造成衝突，
解決方式就是不要讓中心有顯示該箱子的資訊，
然後用TNT讓箱子內的物品銷毀。

**Comment by frank89722** [comment]
這是修不好的東西，模組問題

**Comment by frank89722** [comment]
停止維護SLCP3.1
